CONSUL_VERSION=0.9.3
REPLICATE_VERSION=0.4.0
TEMPLATE_VERSION=0.19.3
ENVCONSUL_VERSION=0.7.2
HASHIUI_VERSION=0.18.0
NOMAD_VERSION=0.6.3
PACKER_VERSION=1.1.0
TERRAFORM_VERSION=0.10.4
VAULT_VERSION=0.8.2

CONSUL_ITERATION=2
ENVCONSUL_ITERATION=2
HASHIUI_ITERATION=1
NOMAD_ITERATION=1
PACKER_ITERATION=1
REPLICATE_ITERATION=2
TEMPLATE_ITERATION=2
TERRAFORM_ITERATION=1
VAULT_ITERATION=3

PACKAGER="Gavin M. Roy <gavinr@aweber.com>"
ARCH=amd64

clean:
	@( rm -rf build/* )
	@( rm -rf dist/* )
	@( rm -rf downloads/* )

-include download.mk
-include deb.mk
