CONSUL_VERSION=1.0.0
REPLICATE_VERSION=0.4.0
TEMPLATE_VERSION=0.19.4
ENVCONSUL_VERSION=0.7.2
HASHIUI_VERSION=0.22.0
NOMAD_VERSION=0.6.3
PACKER_VERSION=1.1.1
TERRAFORM_VERSION=0.10.8
VAULT_VERSION=0.8.3

CONSUL_ITERATION=1
ENVCONSUL_ITERATION=2
HASHIUI_ITERATION=1
NOMAD_ITERATION=2
PACKER_ITERATION=1
REPLICATE_ITERATION=2
TEMPLATE_ITERATION=1
TERRAFORM_ITERATION=1
VAULT_ITERATION=1

PACKAGER="Gavin M. Roy <gavinr@aweber.com>"
ARCH=amd64

clean:
	@( rm -rf build/* )
	@( rm -rf dist/* )
	@( rm -rf downloads/* )

-include download.mk
-include deb.mk
